name: CI

on: 
  push:
  pull_request:

jobs:
  windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - run: choco install nasm
      # nasm is not installed into the $PATH so add it manually
      - run: echo "C:\Program Files\NASM" >> $env:GITHUB_PATH
      - run: nasm -v
      - run: make OS=msvc gmp-bootstrap
      - run: make OS=msvc gtest-bootstrap
      - working-directory: ./build
        env:
          CFLAGS: -WX
        run: ./AutoBuildForWindows.bat Win64-Release-C
      - run: ./bin/x64/Release/codec_unittest.exe
      - uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: bin/x64/Release
      - uses: softprops/action-gh-release@v1
        with:
          files: "bin/x64/**"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
